# Generated by Django 5.0.3 on 2024-04-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Age', models.IntegerField(default='')),
                ('contact', models.IntegerField(default='')),
                ('mail', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
